function noTry(fn, handleErr = error => null) {
    const result = [null, null];
    try {
        result[0] = fn();
    }
    catch (err) {
        result[1] = err;
        handleErr(err);
    }
    return result;
}
async function noTryAsync(fn, handleErr = error => null) {
    const result = [null, null];
    try {
        result[0] = await fn();
    }
    catch (err) {
        result[1] = err;
        handleErr(err);
    }
    return result;
}

export { noTry, noTryAsync };
