function noTry(fn, handleErr = error => null) {
    const result = { result: null, error: null };
    try {
        result.result = fn();
    }
    catch (err) {
        result.error = err;
        handleErr(err);
    }
    return result;
}
async function noTryAsync(fn, handleErr = error => null) {
    const result = { result: null, error: null };
    try {
        result.result = await fn();
    }
    catch (err) {
        result.error = err;
        handleErr(err);
    }
    return result;
}

export { noTry, noTryAsync };
